---
title: "Devon's_Playaround_space"
output: html_document
date: "2025-11-13"
---


```{r}
 library(haven)
library(tidyverse)
```


```{r}
liver_data_raw = read_sas("/Users/devonpark/Library/CloudStorage/OneDrive-ColumbiaUniversityIrvingMedicalCenter/tx_li.sas7bdat")

```


```{r}
liver_data = liver_data_raw |> 
  mutate(tx_date = as.Date(REC_TX_DT),
listing_date = as.Date(CAN_LISTING_DT),
tx_year = year(tx_date),
days_listed = as.numeric(difftime(tx_date, listing_date, units = "days"))) %>% # days on waitlist
filter(!is.na(PERS_ID) & !is.na(tx_date) & tx_year >= 2002 & REC_AGE_AT_TX >= 18) %>%# MELD era only, Adults only
arrange(PERS_ID, tx_date) |> 
  janitor::clean_names()
```


Looking at race:
```{r}
#Clean don_Race column

liver_data_clean = 
liver_data |> 
  mutate(
    
    don_race_raw = don_race,#Clean original race codes
    true_missing = is.na(don_race_raw) | don_race_raw %in% c("NA", "", " "), # 2. Identify TRUE missing before numeric conversion
   
    don_race_num = suppressWarnings(as.numeric(trimws(as.character(don_race_raw)))),  #Converts to numeric (will produce NA for non-numeric multi-racial codes)

    don_race = case_when(
      don_race_num == 8 ~ "White",
      don_race_num == 16 ~ "Black or African American",
      don_race_num == 32 ~ "American Indian or Alaska Native",
      don_race_num == 64 ~ "Asian",
      don_race_num == 128 ~ "Native Hawaiian or Other Pacific Islander",
      don_race_num == 256 ~ "Arab or Middle Eastern",
      don_race_num == 512 ~ "Indian Sub-continent",
      don_race_num == 1024 ~ "Unknown (for Donor Referral only)",
      don_race_num == 2000 ~ "Hispanic/Latino",

      don_race_num %in% c(24, 40, 48, 56, 72, 80, 88, 96, 104, 112, 120, 
                          136, 144, 192, 200, 232) ~ "Multi-Racial",

      true_missing ~ "Missing", #see if there are TRUE missing BEFORE numeric conversion

      is.na(don_race_num) ~ "Multi-Racial", #Numeric conversion failures → Multi-Racial (your new rule)

      TRUE ~ as.character(don_race_raw) #Fallback in case
    )
  ) 
  
```



```{r}
liver_data_clean |> 
  distinct(don_race_srtr)

liver_data_clean = 
  liver_data_clean |>
    mutate(
      don_race_srtr_std = don_race_srtr,
      don_race_srtr_std = case_when(
        don_race_srtr_std == "ASIAN"   ~ "Asian",
        don_race_srtr_std == "WHITE"   ~ "White",
        don_race_srtr_std == "BLACK"   ~ "Black or African American",
        don_race_srtr_std == "NATIVE"  ~ "American Indian or Alaska Native",
        don_race_srtr_std == "MULTI"   ~ "Multi-Racial",
        don_race_srtr_std == "PACIFIC" ~ "Native Hawaiian or Other Pacific Islander",
        don_race_srtr_std == ""        ~ "NOT SPECIFIED",
        TRUE ~ don_race_srtr_std #For all rows that did not match any of the previous recoding conditions, keep the original value
      )
    )
  

```

```{r}
# Visualise don_race

liver_data_clean |>
  count(don_race, sort = TRUE) |>
  mutate(pct = n / sum(n) * 100) |>
  ggplot(aes(x = n, y = reorder(don_race, n))) +
  geom_col(fill = "steelblue") +
  geom_text(aes(label = paste0(round(pct, 3), "%")), 
            hjust = -0.1, size = 3.5) +
  labs(
    title = "Distribution of Donor Race",
    x = "Count",
    y = "Race"
  ) +
  theme_minimal() +
  xlim(0, max(liver_data_clean |> count(don_race) |> pull(n)) * 1.15)
```


Plot for don_Race_srtr_std:
```{r}
liver_data_clean |>
  count(don_race_srtr_std, sort = TRUE) |>
  mutate(pct = n / sum(n) * 100) |>
  ggplot(aes(x = n, y = reorder(don_race_srtr_std, n))) +
  geom_col(fill = "steelblue") +
  geom_text(aes(label = paste0(round(pct, 3), "%")), 
            hjust = -0.1, size = 3.5) +
  labs(
    title = "Distribution of Donor Race",
    x = "Count",
    y = "Race"
  ) +
  theme_minimal() +
  xlim(0, max(liver_data_clean |> count(don_race_srtr_std) |> pull(n)) * 1.15)
```


Check for mismatches between don_race and don_race_srtr (but actually don_Race_srtr_std)
```{r}
#FILTER OUT ROWS THAT ARE counted as "Unknown (for Donor Referral only)" in don_race
mismatched_race_x = 
  liver_data_clean |> 
  select(pers_id, don_race, don_race_srtr_std) |>
  filter(don_race != "Unknown (for Donor Referral only)") |> 
  mutate(
    race_match = don_race == don_race_srtr_std #creates a logical vector
  ) |> 
  filter(race_match == FALSE)


mismatched_race_y = 
  liver_data_clean |> 
  select(pers_id, don_race, don_race_srtr_std) |>
  filter(don_race == "Unknown (for Donor Referral only)") |> 
  mutate(
    race_match = don_race == don_race_srtr_std #creates a logical vector
  ) |> 
  filter(race_match == FALSE)

```


Look at deceased vs living donors and gender

```{r}
liver_data_clean |> count(don_ty)
liver_data_clean |> count(don_gender)
liver_data_clean |> filter(don_ty == "L" | don_ty == "C") |> count(don_gender)
liver_data_clean |> filter(don_ty == "C") |> count(don_gender)
liver_data_clean |> filter(don_ty == "L") |> count(don_gender)

```

Look at citizenship
```{r}
liver_data_clean |> count(don_citizenship)
#916 NA values

#Code	Description
#1	1: US Citizen
#2	2: Resident Alien
#3	3: Non-Resident Alien, Specify Country
#4	4: Non-US Citizen/US Resident
#5	5: Non-US Citizen/Non-US Resident
#998	998: Unknown
```


Donor cause of death:
```{r}

liver_data_clean |> count(don_cad_don_cod)
#7120 NA values

#Code	Description
#1	1: ANOXIA
#2	2: CEREBROVASCULAR/STROKE
#3	3: HEAD TRAUMA
#4	4: CNS TUMOR
#998	998: UNKNOWN
#999	999: OTHER SPECIFY
```


Donor death Circumstance 
```{r}

liver_data_clean |> count(don_death_mech)

#Code	Description
#1	1: MVA
#2	2: SUICIDE
#3	3: HOMICIDE
#4	4: CHILD-ABUSE
#5	5: NON-MVA
#6	6: DEATH FROM NATURAL CAUSES
#997	997: NONE OF THE ABOVE
#998	998: UNKNOWN
```


Donor death Mechanism
```{r}

liver_data_clean |> count(don_death_circum)

#Code	Description
#1	1: DROWNING
#2	2: SEIZURE
#3	3: DRUG INTOXICATION
#4	4: ASPHYXIATION
#5	5: CARDIOVASCULAR
#6	6: ELECTRICAL
#7	7: GUNSHOT WOUND
#8	8: STAB
#9	9: BLUNT INJURY
#10	10: SIDS
#11	11: INTRACRANIAL HEMORRHAGE/STROKE
#12	12: DEATH FROM NATURAL CAUSES
#995	995: 995-Gunshot/stab wound (Pre-OTIS)
#997	997: NONE OF THE ABOVE
#998	998: UNKNOWN
```


Plot for DECEASED don_Race_srtr_std:
```{r}
liver_data_clean |>
  filter(don_ty == "C") |> 
  count(don_race_srtr_std, sort = TRUE) |>
  mutate(pct = n / sum(n) * 100) |>
  ggplot(aes(x = n, y = reorder(don_race_srtr_std, n))) +
  geom_col(fill = "steelblue") +
  geom_text(aes(label = paste0(round(pct, 2), "%")), 
            hjust = -0.1, size = 3.5) +
  labs(
    title = "Distribution of Deceased Donor Race",
    x = "Count",
    y = "Race"
  ) +
  theme_minimal() +
  xlim(0, 160000)
```


Plot for DECEASED don_Race_srtr_std:
```{r}
liver_data_clean |>
  filter(don_ty == "L") |> 
  count(don_race_srtr_std, sort = TRUE) |>
  mutate(pct = n / sum(n) * 100) |>
  ggplot(aes(x = n, y = reorder(don_race_srtr_std, n))) +
  geom_col(fill = "steelblue") +
  geom_text(aes(label = paste0(round(pct, 2), "%")), 
            hjust = -0.1, size = 3.5) +
  labs(
    title = "Distribution of Living Donor Race",
    x = "Count",
    y = "Race"
  ) +
  theme_minimal() +
  xlim(0, 10000)
```

