---
title: "Final Project"
output: html_document
date: "2025-11-05"
---

The group members:
Elina Stoffel (es3866), Devon Park (dap2189), Olivia Martinez (om2372), Diane Benites (dmb2257)

Tentative project title: Pre- and Post-Transplant Outcomes in Alcohol-Associated Liver Disease: Insights from the UNOS dataset

The motivation for this project: By learning how to clean and analyze larger datasets from online registries, we believe this will equip us to become 

The intended final products: We plan to produce a reproducible R Markdown report and webpage including cleaned data, analysis, and visualizations from the SRTR database. The report will include a table with demographics, outcomes, and statistical analyses including a regression or survival analysis. Finally, there will be an interpretation of our data to be discussed in class.

The anticipated data sources: De-identified data from the SRTR transplant registry 

The planned analyses / visualizations / coding challenges:
- Cleaning/filtering of the dataset to identify adult liver transplant recipients with ALD
- Selecting key predictors and outcomes variables to assess (e.g. age, MELD score, co-morbidities across ALD vs non-ALD groups)
- Post-transplant survival using Kaplam Meier curve or Cox proportional hazards model
- Visualization of some trends over time 
Anticipated challenges include cleaning the data from this larger dataset

The planned timeline:
- Week 1-2 Data-cleaning
- Week 2-3: Data analysis, initial visualizations
- Week 3-4: Statistical analyses, website creation
- Week 4: Compile report, polish visuals